### ISSUE TITLE
Feature request - ModelsBuilder in Vorto

### ISSUE THREAD

**Issue by liamlaverty** [umco/umbraco-vorto#102]
It'd be handy if Vorto worked with ModelsBuilder to produce some strongly typed properties. There's an example of it [here](https://24days.in/umbraco-cms/2015/multilingual-vorto-nested-content/).

**Comment by sniffdk** [comment]
Or perhaps, as a start, an extension method on VortoValue 😄

**Comment by mattbrailsford** [comment]
Closing. We can move the discussion over to PR #107
