### ISSUE TITLE
Votro TextString - fallback to show TextString value on website & backoffice

### ISSUE THREAD

**Issue by kudecha** [umco/umbraco-vorto#106]
Hi,
I have a fully working website in Umbraco with content in english.
Recently started using Vorto plugin to make the website multi lingual.
I have created a wrapper for Textstring datatype using Vorto.
Also updated GetPropertyValue() function on templates to use GetVortoValue().
As soon as I publish the template to website (which uses GetVortoValue() function), it won't show any text on designated field. I understand that I haven't loaded or changed any content yet.
But,
would it not be great to apply a fallback mechanism where if VortoValue is not found, then it may look out for standard value of the property and return it on website?
also, would it be great to pull the TextSTring value in the Vorto TestString field within backoffice when backoffice is accessed for the first time after chane?

Anyone came across this idea and has implemented any code?
Any suggestions?

Thanks,
Jay

**Comment by leekelleher** [comment]
Hi @kudecha, thanks for raising this.  We've started to discuss this very thing on issue https://github.com/umco/umbraco-vorto/issues/105#issuecomment-395012585

We haven't implemented any code to handle this this scenario, (it's still at discussion phase) - unless if a community member wanted to submit a pull-request?

**Comment by kudecha** [comment]
Thanks @leekelleher I will follow the progress on the other thread. I have started figuring out the code myself but not at the stage of a pull-request yet. I hope to spend more time on this over next week and hope to get back with something useful.

**Comment by mattbrailsford** [comment]
Closing issue. Can continue the discussion on issue #105
