### ISSUE TITLE
Vorto API cause blocking when many Vorto properties exist on a document type

### ISSUE THREAD

**Issue by shandybob76** [umco/umbraco-vorto#108]
Hi There,

I had a document with around 50 Vorto properties - it was quite complex, but I found that when loading the content, there were 3 API calls that were repeated per property. Reloading that content also initiated all of the API calls again. Many calls ended up blocking as loading the content page fired off 150+ API calls.

I have a mechanism to cache these and I have forked to make the change - would be ace to be able to get a pull request reviewed for my fork so I'll raise it 👍 

Cheers

Robbo

**Comment by mattbrailsford** [comment]
Closing issue, will continue discussion on PR #109
