### ISSUE TITLE
Issue in nested content template

### ISSUE THREAD

**Issue by SabaTD** [umco/umbraco-vorto#112]
Hi, I am using nested content in carousel. There is {{ Title }} in template tab so I was getting list of slides with Titles not Item1, Item2 and so.  Since i installed Vorto of course the logic destroyed, here is what i got now : http://prntscr.com/lr1pnl

Any ideas how can i filter this json array in template input ?

**Comment by mattbrailsford** [comment]
Easiest thing I tend to do is read the value from whatever is your default language so you can have an NC template like `{{ title.values['en-US'] }}`

**Comment by SabaTD** [comment]
You are goddamn right,  I did not think it :) thanks for help.
