### ISSUE TITLE
Empty fields break JS

### ISSUE THREAD

**Issue by kjac** [umco/umbraco-vorto#48]
If I have a simple text field in multiple languages, and I empty the value of the text field in all languages, the Vorto JS breaks when publishing twice in a row.

Steps:
- Open the JS console :)
- In a Vorto datatype wrapping a simple text field, clean out all values in all languages and hit save and publish.
- Hit save and publish again.
- The console logs JS errors.

I think it's the [assignment of `undefined`](https://github.com/mattbrailsford/umbraco-vorto/blob/master/src/Our.Umbraco.Vorto/Web/UI/App_Plugins/Vorto/js/vorto.js#L203) that causes the issue. If you replace `undefined` with `{}`, it seems to work just fine.

**Comment by dawoe** [comment]
I created a PR in this issue that fixes it for me https://github.com/mattbrailsford/umbraco-vorto/issues/58

**Comment by mattbrailsford** [comment]
Should be fixed in 97d9020 / 075b9cf6dabb8be0cd34859aed0ca070824e456e
