### ISSUE TITLE
TypeError: Cannot read property 'values' of undefined

### ISSUE THREAD

**Issue by runehorneland** [umco/umbraco-vorto#57]
Hi Matt, We're using Umbraco 7.4.1 and from time to time get different Vorto-related errors. It seems to happen "over night" and not specifically when coding and deploying. The errors are present both locally and in out Test-environment in Azure.

In Umbraco backoffice the properties show up empty, and in our logs and console in Chrome we find at least these 3 errors below. Any chance for som work on Vorto + Umbraco 7.4? We're mid-project and can change to dictionary-items, but it will cost us a day or two, plus different workflow with customer for translations. Thank you.

`2016-08-16 12:28:54,592 [70] WARN Odin.Extensions.VortoUrl.ExtensionsForIPublishedContent - System.NullReferenceException: Object reference not set to an instance of an object. at Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.DoHasVortoValue(IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive) at Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.HasVortoValue(IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, String fallbackCultureName) at Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.DoGetVortoValue[T](IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue) at Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.GetVortoValue[T](IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue, String fallbackCultureName) at Odin.Extensions.VortoUrl.ExtensionsForIPublishedContent.UrlPart(IPublishedContent this, String culture) in C:\projects\ODIN online\Umbraco\Odin\Extensions\VortoUrl\ExtensionsForIPublishedContent.cs:line 20`

`angular.min.js?cdv=1930127862:63 TypeError: Cannot read property 'values' of undefined at link (http://dev.odinonline.no/App_Plugins/Vorto/js/vorto.js?cdv=1930127862:392:44) at k (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:44:444) at e (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:40:139) at k (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:44:382) at e (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:40:139) at http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:39:205 at http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:162:213 at Object.fn (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:90:12) at Object.$digest (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:90:356) at Object.$apply (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:92:431)`

`TypeError: Cannot read property 'no' of undefined at link (http://dev.odinonline.no/App_Plugins/Vorto/js/vorto.js?cdv=1930127862:392:51) at k (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:44:444) at e (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:40:139) at k (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:44:382) at e (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:40:139) at http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:39:205 at http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:162:213 at Object.fn (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:90:12) at Object.$digest (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:90:356) at Object.$apply (http://dev.odinonline.no/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1930127862:92:431)`

**Comment by dawoe** [comment]
I was having similar issues that are fixed in PR for https://github.com/mattbrailsford/umbraco-vorto/issues/58

Maybe you can test as well

**Comment by mattbrailsford** [comment]
Should be fixed in 97d9020 / 075b9cf6dabb8be0cd34859aed0ca070824e456e
