### ISSUE TITLE
Cannot set property 'en-US' of null error with empty fields

### ISSUE THREAD

**Issue by dawoe** [umco/umbraco-vorto#58]
Hi Matt,

We see above error in the console of the browser with Vorto fields that doesn't have values yet.

Steps to reproduce
1. Create a vorto datatype for textstring and add it to a doctype.
2. Create a new item based on this doctype. Don't fill in any fields and click on Save and Publish.
3. Switch to another language and you will see the error

I noticed in the umbraco.config file that the value is null.
<title><![CDATA[{"values":null,"dtdGuid":"33da4dc8-510b-453b-8c6a-3b340e47db02"}]]></title>

Using Umbraco 7.4.3 with latest Vorto release.

Probably related to this items :
https://github.com/mattbrailsford/umbraco-vorto/issues/57
https://github.com/mattbrailsford/umbraco-vorto/issues/48

**Comment by takinosaji** [comment]
was this change released?
