### ISSUE TITLE
Not working with Umbraco MultipleMediaPicker

### ISSUE THREAD

**Issue by ryanology** [umco/umbraco-vorto#65]
I created a Vorto type that uses a multimediapicker data type, but I am unable to actually add any images.  The MMP is configured to start in a specific media folder, but when trying to add an image the Select Media modal window does not actually start in that folder.  And if I try to drag/drop or upload an image, it just changes my browser URL to the location of the file on my local system. And if I try to click the Media link in that modal window (to go back to the root media folder), it actually redirects me to the backoffice default landing page (/umbraco/#/).

I have tried it with the Legacy Media Picker and am getting the same results.  Seems my only option right now is to use a MNTP, but unfortunately that does not show the selected image in the backoffice.

Running v7.4.3 on Umbraco as a Service with Vorto 1.5.2 and ImageProcessor using an Azure storage CDN.

**Comment by ryanology** [comment]
I'm wondering if anyone else has either been able to reproduce this error, or if anyone has been able to successfully use the multimediapicker inside of a Vorto property.

Another thing that I've noticed is that there is an angular error in Chrome dev tools when I actually click the icon to select an image:
SyntaxError: Unexpected token b in JSON at position 1               angular.min.js?cdv=562372413:63
    at Object.ub [as fromJson] (angular.min.js?cdv=562372413:13)
    at Object.get (angular-cookies.min.js?cdv=562372413:7)
    at new <anonymous> (umbraco.controllers.js?cdv=562372413:3403)
    at d (angular.min.js?cdv=562372413:28)
    at Object.instantiate (angular.min.js?cdv=562372413:28)
    at angular.min.js?cdv=562372413:53
    at angular.min.js?cdv=562372413:44
    at n (angular.min.js?cdv=562372413:7)
    at k (angular.min.js?cdv=562372413:44)
    at e (angular.min.js?cdv=562372413:40)

And I've just upgraded Umbraco to 7.5.3 hoping that might fix it, but I'm still not able to select an image.
Thanks

**Comment by alindgren** [comment]
This may be related to this Umbraco issue: http://issues.umbraco.org/issue/U4-9312

Should test with Umbraco 7.5.8.

**Comment by mattbrailsford** [comment]
Unless anyone confirms otherwise, I'll assume this was releated to the issue linked above and should be resovled in latest umbraco versions.
