### ISSUE TITLE
'VortoValue' does not contain a contructor that takes 0 arguments

### ISSUE THREAD

**Issue by rasmuseeg** [umco/umbraco-vorto#73]
Updated to nuget version 1.5.3 and exspected the VortoValue to be public, as changed about 3 months ago. 
Does not appear to be public.

The .dll from the zip-package does have a constructor on VortoValue that is public
But doesn't have the #63 fix.

**Comment by JimBobSquarePants** [comment]
I'm running Vorto 1.5.3 and VortoValue is both public and has a parameterless public constructor.

I can confirm though that the #63 fix is missing from that release.

**Comment by mattbrailsford** [comment]
I believe this should be fixed now as the #63 fix is in the codebase. Feel free to re-open if that appears not to be the case.
