### ISSUE TITLE
Vorto failed to convert db value when vorto does not have the DtdGuid

### ISSUE THREAD

**Issue by rasmuseeg** [umco/umbraco-vorto#74]
When setting propertyvalue to VortoValue with empty DtdGuid, getting vorto value from frontend breaks. Why is the DtdGuid even required, shouldn't vorto resolve this from the prevalue collection?

**Comment by mattbrailsford** [comment]
Because at some point in the code chain there is a point at which the property editor has no context when abiding by the public methods in Umbraco so we have to stash the GUID at a point we do know it so we can access it later on.

**Comment by mattbrailsford** [comment]
As mentioned, this is required due to an issue in the umbraco api points so is not a bug. If you are setting the VortoValue manually, you'll have to set the DtdGuid

**Comment by rasmuseeg** [comment]
Wouldn't it make ideal fallback on `Umbraco.Textarea` or `Umbraco.Textstring`?

**Comment by mattbrailsford** [comment]
I'd need to think through the whole model and check the code that uses it to see if it would be a problem, unfortunately I'm really low on time atm so it's gonna be pretty low priority.

Feel free to test / PR if you like and I can review what you come up with.

**Comment by rasmuseeg** [comment]
Sure, i might do that. I was thinking about taking a look at the core of Archetype to see how they resolve configured data types.

Den 5. dec. 2016 5.34 PM skrev Matt Brailsford <notifications@github.com>:

I'd need to think through the whole model and check the code that uses it to see if it would be a problem, unfortunately I'm really low on time atm so it's gonna be pretty low priority.

Feel free to test / PR if you like and I can review what you come up with.
