### ISSUE TITLE
Add possiblity to show a global language switch for the whole node

### ISSUE THREAD

**Issue by simonech** [umco/umbraco-vorto#80]
If you have many vorto-enabled fields in a node, it would be nice to be able to show a global language switcher at the top of the page, that switches all fields of the node.

**Comment by ryanmcdonough** [comment]
If you have sync enabled then changing one will do all of them anyway.

**Comment by simonech** [comment]
I know... I mean so that the menu appears only one property

**Comment by mattbrailsford** [comment]
Given the languages feature coming in v8, I don't think this is worth looking at in vorto now.
