### ISSUE TITLE
No info about active language in cookies untill language tab switch

### ISSUE THREAD

**Issue by andreygarmash** [umco/umbraco-vorto#82]
Steps to reproduce:

1. load umbraco backoffice in incognito mode
2. select a page that contains vorto field

Expected result: localStorage.getItem('vortoActiveLanguage') returns currently selected language (default)
Actual: localStorage.getItem('vortoActiveLanguage') returns undefined

**Comment by mattbrailsford** [comment]
Why are you accessing the local storage item? I'm not sure exactly what the bug here is? Is the undefined causing a problem in vorto? or are you trying to use it somewhere outside of a vorto context?

**Comment by mattbrailsford** [comment]
Closing until an actual bug is identified. Feel free to re-open with further information.
