### ISSUE TITLE
UI Position Issue

### ISSUE THREAD

**Issue by craigs100** [umco/umbraco-vorto#94]
Umb 7.7.3, Vorto 1.5.3, Tested in Chrome 61 and Firefox 55

When editing a Vorto wrapped Grid editor, the div containing the "Reorder" control occludes the Vorto tab by 15px. Not sure if this should be raised here or with Umbraco. Trying here first.

![screenshot from 2017-10-21 11-19-56](https://user-images.githubusercontent.com/1143883/31851716-44eff1fe-b663-11e7-875e-32fc58e610a2.png)

**Comment by mattbrailsford** [comment]
That's a grid CSS issue not Vorto. The best option would be to use this technique https://24days.in/umbraco-cms/2015/umbraco-7-back-office-tweaks/ to load in a custom CSS style sheet and tweak the layout accordingly.
