### ISSUE TITLE
Make the package more strongly typed (generic typed)

### ISSUE THREAD

**Issue by DennisBoonkP** [umco/umbraco-vorto#98]
Is it possible we make Vorto even more strongly typed with Modelsbuilder?
Maybe we can make the VortoValue class generic like this VortoValue<T> and let the T be determined by Modelsbuilder based on the selected child data type (data type to wrap) for the Vorto data type instance. 
For example (data type, T):
RTE, IHtmlString
TextString, string
Numeric, int
Multi node tree picker, IEnumerable<IPublishedContent>

I think this can be realised with one PropertyValueConverter and the usage of some umbraco api's. Maybe some smart caching for performance, but don't think it would be necessary.
I would also prefer a getter for the value, so the syntax in razor would be something like this:
(User docType object, Function VortoValue<string> property) 
`<span>@User.Function.Get("nl")</span>` or 
`<span>@User.Function.Get(Culture)</span>` or 
`@{CultureInfo ci = ... }<span>@User.Function.Get(ci)</span>`
So no need for casting anymore :) Let me know what you think!

**Comment by mattbrailsford** [comment]
Closing as will be resolved by PR #107
