### ISSUE TITLE
Recursive GetVortoValue -> NullReferenceException

### ISSUE THREAD

**Issue by drangus** [umco/umbraco-vorto#99]
Following an upgrade from Vorto 1.5.3 to 1.6.0, calling GetVortoValue with the recursive parameter set true fails with a NullReferenceException (... at line 98 of IPublishedContentExtensions.cs)

Testing for a null value appears to address the issue:
```
        var prop = content.GetProperty(propertyAlias);
        if (prop != null)
        {...
```
Is this an appropriate workaround?

(Umbraco 7.5.11)

**Comment by SitePointGmbH** [comment]
A workaround would be great. Have a productive web running and this function is essentiell....

**Comment by leekelleher** [comment]
@drangus How are your dev skills? Would be great if you could make a pull-request! 😎 
(Since you spotted the issue and have a workaround patch, you should get commit credit)

**Comment by drangus** [comment]
@leekelleher First attempt at a PR! Trust it meets requirements.

**Comment by SitePointGmbH** [comment]
Great Workarround. Fixed the problem with me.
For those who don't want to download the vs-Project  and compile it, here is the fixed dll:
https://www.dropbox.com/s/2n9q8chrkrglgxr/Our.Umbraco.Vorto.dll?dl=0

**Comment by leekelleher** [comment]
Thanks @drangus!

Closing this ticket off, any discussion can be done on PR #100

**Comment by jbreuer** [comment]
Is this the same issue as this? https://github.com/umco/umbraco-vorto/issues/41
For now I downgraded back to Vorto 1.5.3.

**Comment by tomvanenckevort** [comment]
I've just run into the same issue when I upgraded a site from v7.5.14 to v7.11.1 and then also upgraded Vorto from v1.5.3 to v1.6.0. Downgrading it back to v1.5.3 fixes the issue for now.

**Comment by tommyTanaka** [comment]
Any news about this issue? Just upgraded to 1.6.0 and run into this error ....
